CREATE STREAMING TABLE usa.geospatial_scott_stafford.bronze_national_address AS
  SELECT
    OID_, 
    AddNum_Pre, 
    Add_Number, 
    AddNum_Suf, 
    AddNo_Full,
    St_PreMod, 
    St_PreDir, 
    St_PreTyp, 
    St_PreSep, 
    St_Name,
    St_PosTyp, 
    St_PosDir, 
    St_PosMod, 
    StNam_Full, 
    Building, 
    Floor, 
    Unit, 
    Room, 
    Seat, 
    Addtl_Loc, 
    SubAddress, 
    LandmkName, 
    County, 
    Inc_Muni, 
    Post_City, 
    Census_Plc, 
    Uninc_Comm,
    Nbrhd_Comm,
    NatAmArea, 
    NatAmSub, 
    Urbnztn_PR, 
    PlaceOther,
    PlaceNmTyp, 
    State, 
    Zip_Code, 
    Plus_4, 
    UUID, 
    AddAuth,
    AddrRefSys, 
    DOUBLE(Longitude) as Longitude, 
    Double(Latitude) as Latitude, 
    NatGrid, 
    Elevation,
    Placement, 
    AddrPoint, 
    Related_ID, 
    RelateType, 
    ParcelSrc,
    Parcel_ID, 
    AddrClass, 
    Lifecycle, 
    Effective, 
    Expire,
    DateUpdate, 
    AnomStatus, 
    LocatnDesc, 
    Addr_Type, 
    DeliverTyp,
    NAD_Source, 
    DataSet_ID
  FROM
    STREAM read_files(
      concat("/Volumes/usa/geospatial_scott_stafford/data/nad"),
      format => "csv",
      header => true,
      schema => 'OID_ STRING, AddNum_Pre STRING, Add_Number STRING, AddNum_Suf STRING, AddNo_Full STRING,
    St_PreMod STRING, St_PreDir STRING, St_PreTyp STRING, St_PreSep STRING, St_Name STRING,
    St_PosTyp STRING, St_PosDir STRING, St_PosMod STRING, StNam_Full STRING, Building STRING, Floor
    STRING, Unit STRING, Room STRING, Seat STRING, Addtl_Loc STRING, SubAddress STRING, LandmkName
    STRING, County STRING, Inc_Muni STRING, Post_City STRING, Census_Plc STRING, Uninc_Comm STRING,
    Nbrhd_Comm STRING, NatAmArea STRING, NatAmSub STRING, Urbnztn_PR STRING, PlaceOther STRING,
    PlaceNmTyp STRING, State STRING, Zip_Code STRING, Plus_4 STRING, UUID STRING, AddAuth STRING,
    AddrRefSys STRING, Longitude STRING, Latitude STRING, NatGrid STRING, Elevation STRING,
    Placement STRING, AddrPoint STRING, Related_ID STRING, RelateType STRING, ParcelSrc STRING,
    Parcel_ID STRING, AddrClass STRING, Lifecycle STRING, Effective STRING, Expire STRING,
    DateUpdate STRING, AnomStatus STRING, LocatnDesc STRING, Addr_Type STRING, DeliverTyp STRING,
    NAD_Source STRING, DataSet_ID STRING'
    )